version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/myapp
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: postgres
